// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
	"encoding/json"
	"time"

	uuid "github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ApiKey struct {
	ID          uuid.UUID    `json:"id"`
	Name        string       `json:"name"`
	HashedToken string       `json:"hashed_token"`
	UserID      uuid.UUID    `json:"user_id"`
	Scopes      []string     `json:"scopes"`
	LastUsedAt  sql.NullTime `json:"last_used_at"`
	ExpiresAt   sql.NullTime `json:"expires_at"`
	CreatedAt   time.Time    `json:"created_at"`
}

type Attachment struct {
	ID          uuid.UUID `json:"id"`
	TicketID    uuid.UUID `json:"ticket_id"`
	Filename    string    `json:"filename"`
	MimeType    string    `json:"mime_type"`
	SizeBytes   int64     `json:"size_bytes"`
	StoragePath string    `json:"storage_path"`
	CreatedAt   time.Time `json:"created_at"`
}

type AuditLog struct {
	ID         uuid.UUID             `json:"id"`
	ActorID    uuid.NullUUID         `json:"actor_id"`
	EntityType string                `json:"entity_type"`
	EntityID   uuid.UUID             `json:"entity_id"`
	Action     string                `json:"action"`
	Before     pqtype.NullRawMessage `json:"before"`
	After      pqtype.NullRawMessage `json:"after"`
	CreatedAt  time.Time             `json:"created_at"`
}

type CannedResponse struct {
	ID         uuid.UUID     `json:"id"`
	Name       string        `json:"name"`
	Body       string        `json:"body"`
	CategoryID uuid.NullUUID `json:"category_id"`
	TypeID     uuid.NullUUID `json:"type_id"`
	SortOrder  int32         `json:"sort_order"`
	CreatedAt  time.Time     `json:"created_at"`
}

type Category struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	SortOrder int32     `json:"sort_order"`
	Active    bool      `json:"active"`
}

type CustomFieldAssignment struct {
	ID            uuid.UUID `json:"id"`
	FieldDefID    uuid.UUID `json:"field_def_id"`
	ScopeType     string    `json:"scope_type"`
	ScopeID       uuid.UUID `json:"scope_id"`
	SortOrder     int32     `json:"sort_order"`
	VisibleOnNew  bool      `json:"visible_on_new"`
	RequiredOnNew bool      `json:"required_on_new"`
}

type CustomFieldDef struct {
	ID        uuid.UUID             `json:"id"`
	Name      string                `json:"name"`
	FieldType string                `json:"field_type"`
	Options   pqtype.NullRawMessage `json:"options"`
	SortOrder int32                 `json:"sort_order"`
	Active    bool                  `json:"active"`
	CreatedAt time.Time             `json:"created_at"`
}

type Group struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

type GroupMember struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

type GroupScope struct {
	GroupID    uuid.UUID     `json:"group_id"`
	CategoryID uuid.UUID     `json:"category_id"`
	TypeID     uuid.NullUUID `json:"type_id"`
}

type Item struct {
	ID        uuid.UUID `json:"id"`
	TypeID    uuid.UUID `json:"type_id"`
	Name      string    `json:"name"`
	SortOrder int32     `json:"sort_order"`
	Active    bool      `json:"active"`
}

type OauthClient struct {
	ID           uuid.UUID `json:"id"`
	ClientID     string    `json:"client_id"`
	HashedSecret string    `json:"hashed_secret"`
	Name         string    `json:"name"`
	Scopes       []string  `json:"scopes"`
	CreatedAt    time.Time `json:"created_at"`
}

type PendingRegistration struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	DisplayName  string    `json:"display_name"`
	PasswordHash string    `json:"password_hash"`
	Token        uuid.UUID `json:"token"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Plugin struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Version     string    `json:"version"`
	Description string    `json:"description"`
	Author      string    `json:"author"`
	Runtime     string    `json:"runtime"`
	Hooks       []string  `json:"hooks"`
	Enabled     bool      `json:"enabled"`
	WasmPath    string    `json:"wasm_path"`
	InstalledAt time.Time `json:"installed_at"`
}

type Setting struct {
	Key   string          `json:"key"`
	Value json.RawMessage `json:"value"`
}

type SlaPolicy struct {
	ID                  uuid.UUID     `json:"id"`
	Name                string        `json:"name"`
	Priority            string        `json:"priority"`
	CategoryID          uuid.NullUUID `json:"category_id"`
	ResponseTargetMin   int32         `json:"response_target_min"`
	ResolutionTargetMin int32         `json:"resolution_target_min"`
}

type SlaRecord struct {
	TicketID             uuid.UUID    `json:"ticket_id"`
	PolicyID             uuid.UUID    `json:"policy_id"`
	FirstResponseAt      sql.NullTime `json:"first_response_at"`
	ResolvedAt           sql.NullTime `json:"resolved_at"`
	ResponseBreachedAt   sql.NullTime `json:"response_breached_at"`
	ResolutionBreachedAt sql.NullTime `json:"resolution_breached_at"`
}

type Status struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Kind      string    `json:"kind"`
	SortOrder int32     `json:"sort_order"`
	Color     string    `json:"color"`
	Active    bool      `json:"active"`
}

type Tag struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	CreatedAt time.Time    `json:"created_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Ticket struct {
	ID              uuid.UUID      `json:"id"`
	TrackingNumber  string         `json:"tracking_number"`
	Subject         string         `json:"subject"`
	Description     string         `json:"description"`
	CategoryID      uuid.UUID      `json:"category_id"`
	TypeID          uuid.NullUUID  `json:"type_id"`
	ItemID          uuid.NullUUID  `json:"item_id"`
	Priority        string         `json:"priority"`
	StatusID        uuid.UUID      `json:"status_id"`
	AssigneeUserID  uuid.NullUUID  `json:"assignee_user_id"`
	AssigneeGroupID uuid.NullUUID  `json:"assignee_group_id"`
	ReporterUserID  uuid.NullUUID  `json:"reporter_user_id"`
	GuestEmail      sql.NullString `json:"guest_email"`
	ResolutionNotes sql.NullString `json:"resolution_notes"`
	ResolvedAt      sql.NullTime   `json:"resolved_at"`
	ClosedAt        sql.NullTime   `json:"closed_at"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	GuestName       string         `json:"guest_name"`
	GuestPhone      string         `json:"guest_phone"`
	SearchVector    interface{}    `json:"search_vector"`
}

type TicketCustomFieldValue struct {
	TicketID   uuid.UUID `json:"ticket_id"`
	FieldDefID uuid.UUID `json:"field_def_id"`
	Value      string    `json:"value"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type TicketLink struct {
	SourceTicketID uuid.UUID `json:"source_ticket_id"`
	TargetTicketID uuid.UUID `json:"target_ticket_id"`
	LinkType       string    `json:"link_type"`
}

type TicketReply struct {
	ID             uuid.UUID      `json:"id"`
	TicketID       uuid.UUID      `json:"ticket_id"`
	AuthorID       uuid.NullUUID  `json:"author_id"`
	GuestToken     sql.NullString `json:"guest_token"`
	Body           string         `json:"body"`
	Internal       bool           `json:"internal"`
	CreatedAt      time.Time      `json:"created_at"`
	NotifyCustomer bool           `json:"notify_customer"`
}

type TicketStatusHistory struct {
	ID              uuid.UUID     `json:"id"`
	TicketID        uuid.UUID     `json:"ticket_id"`
	FromStatusID    uuid.NullUUID `json:"from_status_id"`
	ToStatusID      uuid.UUID     `json:"to_status_id"`
	ChangedByUserID uuid.NullUUID `json:"changed_by_user_id"`
	CreatedAt       time.Time     `json:"created_at"`
}

type TicketTag struct {
	TicketID uuid.UUID `json:"ticket_id"`
	TagID    uuid.UUID `json:"tag_id"`
}

type Type struct {
	ID         uuid.UUID `json:"id"`
	CategoryID uuid.UUID `json:"category_id"`
	Name       string    `json:"name"`
	SortOrder  int32     `json:"sort_order"`
	Active     bool      `json:"active"`
}

type User struct {
	ID           uuid.UUID    `json:"id"`
	Email        string       `json:"email"`
	DisplayName  string       `json:"display_name"`
	Role         string       `json:"role"`
	PasswordHash string       `json:"password_hash"`
	MfaSecret    string       `json:"mfa_secret"`
	MfaEnabled   bool         `json:"mfa_enabled"`
	SamlSubject  string       `json:"saml_subject"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
	OidcSubject  string       `json:"oidc_subject"`
	Disabled     bool         `json:"disabled"`
}

type WebhookConfig struct {
	ID        uuid.UUID `json:"id"`
	Url       string    `json:"url"`
	Events    []string  `json:"events"`
	Secret    string    `json:"secret"`
	Enabled   bool      `json:"enabled"`
	CreatedAt time.Time `json:"created_at"`
}
