// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
	"encoding/json"

	uuid "github.com/google/uuid"
)

type Querier interface {
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error
	AddGroupScope(ctx context.Context, arg AddGroupScopeParams) error
	AddTicketTag(ctx context.Context, arg AddTicketTagParams) error
	AdminSetPassword(ctx context.Context, arg AdminSetPasswordParams) error
	ClearMFA(ctx context.Context, id uuid.UUID) error
	CountTicketsByStatus(ctx context.Context, statusID uuid.UUID) (int64, error)
	CountTicketsByStatusForAssignee(ctx context.Context, arg CountTicketsByStatusForAssigneeParams) (int64, error)
	CountTicketsByStatusForReporter(ctx context.Context, arg CountTicketsByStatusForReporterParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error
	CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) error
	CreateCannedResponse(ctx context.Context, arg CreateCannedResponseParams) (CannedResponse, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) error
	// ── Assignments ───────────────────────────────────────────────────────────────
	CreateCustomFieldAssignment(ctx context.Context, arg CreateCustomFieldAssignmentParams) (CustomFieldAssignment, error)
	// ── Field definitions ─────────────────────────────────────────────────────────
	CreateCustomFieldDef(ctx context.Context, arg CreateCustomFieldDefParams) (CustomFieldDef, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) error
	CreateItem(ctx context.Context, arg CreateItemParams) error
	CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) error
	CreatePlugin(ctx context.Context, arg CreatePluginParams) error
	CreateReply(ctx context.Context, arg CreateReplyParams) error
	CreateSLAPolicy(ctx context.Context, arg CreateSLAPolicyParams) error
	CreateSLARecord(ctx context.Context, arg CreateSLARecordParams) error
	CreateStatus(ctx context.Context, arg CreateStatusParams) error
	CreateStatusHistoryEntry(ctx context.Context, arg CreateStatusHistoryEntryParams) error
	CreateTag(ctx context.Context, name string) (Tag, error)
	CreateTicket(ctx context.Context, arg CreateTicketParams) error
	CreateTicketLink(ctx context.Context, arg CreateTicketLinkParams) error
	CreateType(ctx context.Context, arg CreateTypeParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CreateWebhookConfig(ctx context.Context, arg CreateWebhookConfigParams) error
	DeleteAPIKey(ctx context.Context, id uuid.UUID) error
	DeleteAttachment(ctx context.Context, id uuid.UUID) error
	DeleteCannedResponse(ctx context.Context, id uuid.UUID) error
	DeleteCategory(ctx context.Context, id uuid.UUID) error
	DeleteCustomFieldAssignment(ctx context.Context, id uuid.UUID) error
	DeleteCustomFieldValue(ctx context.Context, arg DeleteCustomFieldValueParams) error
	DeleteGroup(ctx context.Context, id uuid.UUID) error
	DeleteItem(ctx context.Context, id uuid.UUID) error
	DeleteOAuthClient(ctx context.Context, id uuid.UUID) error
	DeletePendingRegistration(ctx context.Context, id uuid.UUID) error
	DeletePlugin(ctx context.Context, id string) error
	DeleteSLAPolicy(ctx context.Context, id uuid.UUID) error
	DeleteStatus(ctx context.Context, id uuid.UUID) error
	DeleteTicketLink(ctx context.Context, arg DeleteTicketLinkParams) error
	DeleteType(ctx context.Context, id uuid.UUID) error
	DeleteWebhookConfig(ctx context.Context, id uuid.UUID) error
	DisableUser(ctx context.Context, id uuid.UUID) error
	EnableUser(ctx context.Context, id uuid.UUID) error
	// Category-specific policy takes precedence over a global one (category_id IS NULL).
	FindSLAPolicy(ctx context.Context, arg FindSLAPolicyParams) (SlaPolicy, error)
	GetAPIKeyByHash(ctx context.Context, hashedToken string) (ApiKey, error)
	GetAttachmentByID(ctx context.Context, id uuid.UUID) (Attachment, error)
	GetCannedResponse(ctx context.Context, id uuid.UUID) (CannedResponse, error)
	GetCategory(ctx context.Context, id uuid.UUID) (Category, error)
	GetCustomFieldAssignment(ctx context.Context, id uuid.UUID) (CustomFieldAssignment, error)
	GetCustomFieldDef(ctx context.Context, id uuid.UUID) (CustomFieldDef, error)
	GetGroup(ctx context.Context, id uuid.UUID) (Group, error)
	GetItem(ctx context.Context, id uuid.UUID) (Item, error)
	GetOAuthClientByClientID(ctx context.Context, clientID string) (OauthClient, error)
	GetPendingRegistrationByToken(ctx context.Context, token uuid.UUID) (PendingRegistration, error)
	GetPlugin(ctx context.Context, id string) (Plugin, error)
	GetSLAPolicy(ctx context.Context, id uuid.UUID) (SlaPolicy, error)
	GetSLARecord(ctx context.Context, ticketID uuid.UUID) (SlaRecord, error)
	GetSetting(ctx context.Context, key string) (json.RawMessage, error)
	GetStatus(ctx context.Context, id uuid.UUID) (Status, error)
	GetStatusByName(ctx context.Context, name string) (Status, error)
	GetTagByName(ctx context.Context, name string) (Tag, error)
	GetTicketByID(ctx context.Context, id uuid.UUID) (GetTicketByIDRow, error)
	GetTicketByTrackingNumber(ctx context.Context, trackingNumber string) (GetTicketByTrackingNumberRow, error)
	GetType(ctx context.Context, id uuid.UUID) (Type, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByIDAdmin(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByOIDCSubject(ctx context.Context, oidcSubject string) (User, error)
	GetUserBySAMLSubject(ctx context.Context, samlSubject string) (User, error)
	GetWebhookConfig(ctx context.Context, id uuid.UUID) (WebhookConfig, error)
	ListAPIKeysByUser(ctx context.Context, userID uuid.UUID) ([]ApiKey, error)
	ListActiveTags(ctx context.Context) ([]Tag, error)
	ListAllTags(ctx context.Context) ([]Tag, error)
	ListAllTickets(ctx context.Context, arg ListAllTicketsParams) ([]ListAllTicketsRow, error)
	ListAssignmentsForScope(ctx context.Context, arg ListAssignmentsForScopeParams) ([]ListAssignmentsForScopeRow, error)
	ListAttachments(ctx context.Context, ticketID uuid.UUID) ([]Attachment, error)
	ListAuditByEntity(ctx context.Context, arg ListAuditByEntityParams) ([]AuditLog, error)
	ListCannedResponses(ctx context.Context) ([]CannedResponse, error)
	ListCategories(ctx context.Context, dollar_1 bool) ([]Category, error)
	ListCustomFieldDefs(ctx context.Context) ([]CustomFieldDef, error)
	ListCustomFieldValuesForTicket(ctx context.Context, ticketID uuid.UUID) ([]ListCustomFieldValuesForTicketRow, error)
	ListEnabledWebhookConfigs(ctx context.Context) ([]WebhookConfig, error)
	ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]uuid.UUID, error)
	ListGroupScopes(ctx context.Context, groupID uuid.UUID) ([]GroupScope, error)
	ListGroups(ctx context.Context) ([]Group, error)
	// Returns only groups with exactly this scope (null type = category-level, non-null = type-specific).
	ListGroupsForExactScope(ctx context.Context, arg ListGroupsForExactScopeParams) ([]Group, error)
	ListGroupsForUser(ctx context.Context, userID uuid.UUID) ([]Group, error)
	ListGroupsInScope(ctx context.Context, arg ListGroupsInScopeParams) ([]Group, error)
	ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error)
	ListOAuthClients(ctx context.Context) ([]OauthClient, error)
	ListPlugins(ctx context.Context) ([]Plugin, error)
	ListReplies(ctx context.Context, ticketID uuid.UUID) ([]TicketReply, error)
	ListResolvedTicketsBefore(ctx context.Context, arg ListResolvedTicketsBeforeParams) ([]ListResolvedTicketsBeforeRow, error)
	ListSLAPolicies(ctx context.Context) ([]SlaPolicy, error)
	ListSettings(ctx context.Context) ([]Setting, error)
	ListStatuses(ctx context.Context) ([]Status, error)
	ListTicketLinks(ctx context.Context, sourceTicketID uuid.UUID) ([]TicketLink, error)
	ListTicketStatusHistory(ctx context.Context, ticketID uuid.UUID) ([]ListTicketStatusHistoryRow, error)
	ListTicketTags(ctx context.Context, ticketID uuid.UUID) ([]Tag, error)
	ListTicketsByAssigneeGroup(ctx context.Context, arg ListTicketsByAssigneeGroupParams) ([]ListTicketsByAssigneeGroupRow, error)
	ListTicketsByAssigneeUser(ctx context.Context, arg ListTicketsByAssigneeUserParams) ([]ListTicketsByAssigneeUserRow, error)
	ListTicketsByReporter(ctx context.Context, arg ListTicketsByReporterParams) ([]ListTicketsByReporterRow, error)
	ListTicketsByStatus(ctx context.Context, arg ListTicketsByStatusParams) ([]ListTicketsByStatusRow, error)
	ListTypes(ctx context.Context, arg ListTypesParams) ([]Type, error)
	ListUnassignedTickets(ctx context.Context, arg ListUnassignedTicketsParams) ([]ListUnassignedTicketsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]User, error)
	NextTicketSeq(ctx context.Context) (int64, error)
	RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error
	RemoveGroupScope(ctx context.Context, arg RemoveGroupScopeParams) error
	RemoveTicketTag(ctx context.Context, arg RemoveTicketTagParams) error
	RestoreTag(ctx context.Context, id uuid.UUID) error
	RestoreUser(ctx context.Context, id uuid.UUID) error
	SearchActiveTags(ctx context.Context, name string) ([]Tag, error)
	SearchAllTickets(ctx context.Context, arg SearchAllTicketsParams) ([]SearchAllTicketsRow, error)
	SearchTicketsByAssigneeGroup(ctx context.Context, arg SearchTicketsByAssigneeGroupParams) ([]SearchTicketsByAssigneeGroupRow, error)
	SearchTicketsByAssigneeUser(ctx context.Context, arg SearchTicketsByAssigneeUserParams) ([]SearchTicketsByAssigneeUserRow, error)
	SearchTicketsByReporter(ctx context.Context, arg SearchTicketsByReporterParams) ([]SearchTicketsByReporterRow, error)
	SearchUnassignedTickets(ctx context.Context, arg SearchUnassignedTicketsParams) ([]SearchUnassignedTicketsRow, error)
	SetSetting(ctx context.Context, arg SetSettingParams) error
	SoftDeleteTag(ctx context.Context, id uuid.UUID) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UpdateAPIKeyLastUsed(ctx context.Context, arg UpdateAPIKeyLastUsedParams) error
	UpdateCannedResponse(ctx context.Context, arg UpdateCannedResponseParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
	UpdateCustomFieldAssignment(ctx context.Context, arg UpdateCustomFieldAssignmentParams) error
	UpdateCustomFieldDef(ctx context.Context, arg UpdateCustomFieldDefParams) error
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) error
	UpdateItem(ctx context.Context, arg UpdateItemParams) error
	UpdatePlugin(ctx context.Context, arg UpdatePluginParams) error
	UpdateSLAPolicy(ctx context.Context, arg UpdateSLAPolicyParams) error
	UpdateSLARecord(ctx context.Context, arg UpdateSLARecordParams) error
	UpdateStatus(ctx context.Context, arg UpdateStatusParams) error
	UpdateTicket(ctx context.Context, arg UpdateTicketParams) error
	UpdateTicketCTI(ctx context.Context, arg UpdateTicketCTIParams) error
	UpdateType(ctx context.Context, arg UpdateTypeParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateWebhookConfig(ctx context.Context, arg UpdateWebhookConfigParams) error
	// ── Values ────────────────────────────────────────────────────────────────────
	UpsertCustomFieldValue(ctx context.Context, arg UpsertCustomFieldValueParams) error
	UpsertPendingRegistration(ctx context.Context, arg UpsertPendingRegistrationParams) (PendingRegistration, error)
}

var _ Querier = (*Queries)(nil)
